sudo: required
services:
  - docker

before_install:
  - docker build -t markfreedman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true markfreedman/react-test npm test -- --coverage

after_success:
  - docker build -t markfreedman/multi-client ./client
  - docker build -t markfreedman/multi-nginx ./nginx
  - docker build -t markfreedman/multi-server ./server
  - docker build -t markfreedman/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to Docker Hub
  - docker push markfreedman/multi-client
  - docker push markfreedman/multi-nginx
  - docker push markfreedman/multi-server
  - docker push markfreedman/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-349441121944'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
